default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Jimpa
  host: localhost
  port: 5432 # Default PostgreSQL port

development:
  <<: *default
  database: Tracing

test:
  <<: *default
  database: Tracing

production:
  <<: *default
  database: Tracing
  username: Tracing
#  password: <%#= ENV['YOUR_APP_NAME_DATABASE_PASSWORD'] %>